version: '3'

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=livelook
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=postgres
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    expose:
      - "5432"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  pgbouncer:
    image: edoburu/pgbouncer
    environment:
      - DATABASE_URL=postgres://postgres:qwerty@db/livelook
      - POOL_MODE=session
      - MAX_CLIENT_CONN=500
    expose:
      - "5432"
    depends_on:
      - db
    ports:
      - "127.0.0.1:15433:5432"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  migrate_up:
    image: migrate/migrate
    volumes:
      - ./db/migrate:/migrations:ro
    command: "-path=/migrations/ -database postgres://postgres:qwerty@db:5432/livelook?sslmode=disable up"
    depends_on:
      - db

  migrate_down:
    image: migrate/migrate
    volumes:
      - ./db/migrate:/migrations:ro
    command: "-path=/migrations/ -database postgres://postgres:qwerty@db:5432/livelook?sslmode=disable down 1"
    depends_on:
      - db

  migrate_force:
    image: migrate/migrate
    volumes:
      - ./db/migrate:/migrations:ro
    command: "-path=/migrations/ -database postgres://postgres:qwerty@db:5432/livelook?sslmode=disable force ${VERSION}"
    depends_on:
      - db

  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  imgproxy:
    image: darthsim/imgproxy:latest
    restart: always
    environment:
      IMGPROXY_BIND: ":80"
      IMGPROXY_QUALITY: "95"
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: "/static"
    volumes:
      - ./web/static/uploaded/static:/static
    ports:
      - "3033:80"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

volumes:
  pg-data:
    driver: local
