db:
  name: livelook
  host: localhost
  port: 15433
  user: postgres
  password: qwerty

redis:
  host: localhost
  port: 6379

app:
  hostname: localhost
  port: 3001
  upload_root: web/static/uploaded
  secret_key: foobar

firebase_auth_service:
  addr: 127.0.0.1:50053
