CREATE TYPE "session_state" AS ENUM (
  'idle',
  'broadcast_single',
  'broadcast_multi',
  'viewer'
);

CREATE TYPE "session_media_type" AS ENUM (
  'video',
  'audio'
);

CREATE TABLE "sessions" (
  "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar(255) NOT NULL,
  "title" varchar(255),
  "image_node" integer,
  "image_filename" varchar(1024),
  "is_online" boolean NOT NULL DEFAULT false,
  "state" session_state NOT NULL DEFAULT 'idle',
  "media_type" session_media_type,
  "viewers_count" integer NOT NULL DEFAULT 0,
  "finished_at" timestamp with time zone,
  "created_at" timestamp with time zone NOT NULL,
  "updated_at" timestamp with time zone NOT NULL
);
ALTER TABLE "sessions" ADD CONSTRAINT "uniq_sessions_user_id" UNIQUE ("user_id");
ALTER TABLE "sessions" ADD CONSTRAINT "fk_sessions_user_id" FOREIGN KEY ("user_id")
  REFERENCES "users"("id") ON DELETE CASCADE;
